scrape_configs:
  - job_name: 'parenthesis-service-local'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:7071' ]

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]
